version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs
    ports:
      - '5432:5432'
  redis:
    container_name: redis_container
    image: redis
    restart: always
    ports:
      - '6379:6379'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: flf.2008brasil@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: godandme
    ports:
      - '5050:80'
